channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.5
  - pandas=1.4.3
  - pip=22.1.2
  
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      # - pdfminer.six==20201012
      # - pdfplumber==0.6.0
      # - rpaframework-pdf==5.0.0
      - googletrans==3.1.0a0
      - rpaframework==17.2.0 # https://rpaframework.org/releasenotes.html